const image = {
  logoSejabest: "/images/logoBest/logoBlue.svg",
  logoSejabestWhite: "/images/logoBest/logoWhite.svg",
  logoSejabestGray:"/images/logoBest/logoGray.svg",
  logoBestHub:"/images/logoBest/LogoBestHub.svg",
  logoVertical:"/images/logoBest/Logotipo-vertical-azul.png",
  logoVerticalWhite:"/images/logoBest/Logotipo SejaBestVerticalWhite.svg",
  iconSejaBest:"/images/logoBest/Simbolo-degrade.png",
  iconSejaBestWhite:"/images/logoBest/iconSejaBestWhite.svg",
  bacen:"/images/LogoParceiros/LogoBancoCentraldoBrasil.svg", 
  imagePageUnavailable: "/images/VetorPersonagens.svg",
  bg:{
    manWithPhone:"/images/Home/ImagemHomeGradiente.png",
  },
  depositions:[
    {
      img:"/images/depositions/Depoimento01.png",
      alt:"",
    },
    {
      img:"/images/depositions/Depoimento02.png",
      alt:"",
    },
    {
      img:"/images/depositions/Depoimento03.png",
      alt:"",
    },
  ],
  
  aboutUs:{ 
    photoCEO: "/images/aboutUs/FotoGaspar.png",
    photoCOO: "/images/aboutUs/FotoGabi.png",
    team: "/images/aboutUs/FotosEquipeDesktop.png",
    teamSM: "/images/aboutUs/FotosEquipeMobile.png",
    bestVersion:"/images/aboutUs/MelhorVersao.png",
    pillars: {
      smColor:{
        education: "/images/aboutUs/3Pilares/PilaresEducacaoCorMobile.png",
        humanized: "/images/aboutUs/3Pilares/PilaresExperienciaCorMobile.png",
        technology: "/images/aboutUs/3Pilares/PilaresTecnologiaCorMobile.png",
      },
      sm:{
        education: "/images/aboutUs/3Pilares/PilaresEducacaoPBMobile.png",
        humanized: "/images/aboutUs/3Pilares/PilaresExperienciaPBMobile.png",
        technology: "/images/aboutUs/3Pilares/PilaresTecnologiaPBMobie.png",
      },
      pb:{
        education: "/images/aboutUs/3Pilares/PilaresEducacaoPB.png",
        humanized: "/images/aboutUs/3Pilares/PilaresExperienciaPB.png",
        technology: "/images/aboutUs/3Pilares/PilaresTecnologiaPB.png",
      },
      color:{
        education: "/images/aboutUs/3Pilares/PilaresEducacaoCor.png",
        humanized: "/images/aboutUs/3Pilares/PilaresExperienciaCor.png",
        technology: "/images/aboutUs/3Pilares/PilaresTecnologiaCor.png",
      },
    },

  },
  partner:{
    businessman:"/images/partner/ImagemAbertura.png",
    manIcon:"/images/partner/ImageHomemForma.png",
    mockupTablet:"/images/partner/MockupTablet.png",
  },
  home:{
    phoneProposal:"/images/Home/CelularPropostas.svg",
    phoneLend:"/images/Home/CelularEmprestados.svg",
    phoneRequested:"/images/Home/CelularSolicitacoes.svg",
    phoneMan:"/images/Home/HomemCelularDesktop.png",
    phoneManSM:"/images/Home/HomemCelularMobile.png",
    mockupPhonesDesktopCrop:"/images/Home/MockupPhonesDesktopCrop.png",
    mockupPhonesSM:"/images/Home/MockupPhonesMobile.png",
    photoFooter: "/images/Home/FotoGaspar.png",
    reclameaqui:"/images/Home/reclameaqui.png"
  },
  finanBest:{
    phoneVideo:"/images/finanBest/VideoFinanBestMobile.gif",
    phoneVideoMd:"/images/finanBest/VideoFinanBestTablett.gif",
    photoKeys:"/images/finanBest/FotoMaoChave.png",
  },
  cashBest:{
    phoneVideo:"/images/cashBest/CashBestMobile.gif",
    phoneVideoMd:"/images/cashBest/VídeoCashBestTablet.gif",
    photoMan:"/images/cashBest/FotonaFormaHomem.png",
    sliderPhones:[
      {img:"/images/cashBest/Celulares/01.png", alt:"Válido para imóveis residenciais e comerciais."},
      {img:"/images/cashBest/Celulares/02.png", alt:"As menores parcelas do mercado."},
      {img:"/images/cashBest/Celulares/03.png", alt:"As menores taxas de crédito."},
      {img:"/images/cashBest/Celulares/04.png", alt:"Atendimento humanizado 7 dias por semana."},
      {img:"/images/cashBest/Celulares/05.png", alt:"Prazos de até 20 anos."},
      
    ],
    sliderMoney1:[
      {img:"/images/cashBest/ImagensSeuDinheiro/ReformarOuConstruir.png", alt:"Reformar ou construir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/AbrirUmNegocio.png", alt:"Abrir um negócio."},
      {img:"/images/cashBest/ImagensSeuDinheiro/CapitaldeGiro.png", alt:"Capital de giro."},
      {img:"/images/cashBest/ImagensSeuDinheiro/Investir.png", alt:"Investir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/ObtencaoDeBens.png", alt:"Obtenção de bens."},
      {img:"/images/cashBest/ImagensSeuDinheiro/PagarSuasDividas.png", alt:"Pagar suas dividas."},
    ],
    sliderMoney2:[
      {img:"/images/cashBest/ImagensSeuDinheiro/CapitaldeGiro.png", alt:"Capital de giro."},
      {img:"/images/cashBest/ImagensSeuDinheiro/Investir.png", alt:"Investir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/ObtencaoDeBens.png", alt:"Obtenção de bens."},
      {img:"/images/cashBest/ImagensSeuDinheiro/PagarSuasDividas.png", alt:"Pagar suas dividas."},
      {img:"/images/cashBest/ImagensSeuDinheiro/ReformarOuConstruir.png", alt:"Reformar ou construir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/AbrirUmNegocio.png", alt:"Abrir um negócio."},
    ],
    sliderMoney3:[
      {img:"/images/cashBest/ImagensSeuDinheiro/PagarSuasDividas.png", alt:"Pagar suas dividas."},
      {img:"/images/cashBest/ImagensSeuDinheiro/ReformarOuConstruir.png", alt:"Reformar ou construir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/AbrirUmNegocio.png", alt:"Abrir um negócio."},
      {img:"/images/cashBest/ImagensSeuDinheiro/CapitaldeGiro.png", alt:"Capital de giro."},
      {img:"/images/cashBest/ImagensSeuDinheiro/Investir.png", alt:"Investir."},
      {img:"/images/cashBest/ImagensSeuDinheiro/ObtencaoDeBens.png", alt:"Obtenção de bens."},
    ],
    sliderTutorial:[
      {img:"/images/cashBest/Tutorial/4PassosTela00.png", alt:"É tão simples você precisa só de 4 passos."},
      {img:"/images/cashBest/Tutorial/4PassosTela01.png", alt:"Passo 1 - Simule e solicite. A simulação é feita através do nosso simulador.Em até 20 minutos você tem o resultado, porque seu tempo é valioso."},
      {img:"/images/cashBest/Tutorial/4PassosTela02.png", alt:"Passo 2 - Envie seus documentos. Após o envio, seus documentos serão analisados e será enviado uma proposta concreta."},
      {img:"/images/cashBest/Tutorial/4PassosTela03.png", alt:"Passo 3 - Avaliação do Imóvel. Nesta etapa o imóvel passará por uma avaliação que irá certificar que o mesmo está apto para ser a garantia do processo."},
      {img:"/images/cashBest/Tutorial/4PassosTela04.png", alt:"Passo 4 - Liberação do recurso. Aqui encerramos a operação com êxito, sempre entregando a melhor experiência ao cliente!"},
    ]
  },
  icons:{
    percentageFill:"/images/SejabestIcones/iconePorcentagemFill.svg",
    calendarFill:"/images/SejabestIcones/iconeCalendarioFill.svg",
    calendarOutline:"/images/SejabestIcones/iconeCalendárioOutlineWhite.svg",
    moneyFill:"/images/SejabestIcones/iconeDinheiroFill.svg",
    checkFill:"/images/SejabestIcones/iconeCheckFill.svg",
    errorFill:"/images/SejabestIcones/iconeErradoFill.svg",
    errorDark:"/images/SejabestIcones/iconeErradoDark.svg",
    phoneFill:"/images/SejabestIcones/iconeCelularFill.svg",
    userFill:"/images/SejabestIcones/iconePessoaFill.svg",
    notebookFill:"/images/SejabestIcones/iconeNotebookFill.svg",
    errorBlue: "/images/SejabestIcones/iconeErradoAzul.svg",
    checkBlue:"/images/SejabestIcones/iconeCheckBlue.svg",
    checkCompleto:"/images/SejabestIcones/iconeCheckfillCompleto.svg",
    checkWhite:"/images/SejabestIcones/iconeCheckWhite.svg",
    grafico:"images/SejabestIcones/iconeGráficoBranco.svg",
    setaDireita:"images/SejabestIcones/iconeSetaDireita.svg",
    setaBaixo:"images/SejabestIcones/iconeSetaBaixo.svg",
      outline:{
        whiteBlueClock:"/images/SejabestIcones/WhiteAndBlue/iconeRelógio.svg",
        whiteBluePhone:"/images/SejaBestIcones/WhiteAndBlue/iconeCelularOutline.svg",
        whiteBlueCalendar:"/images/SejaBestIcones/WhiteAndBlue/iconeCalendárioOutline.svg",
        whiteBlueMoney:"/images/SejaBestIcones/WhiteAndBlue/iconeDinheiroOutline.svg",
      },
  },
  logoMedia: {
    gray:{
      agenciaOGlobo:"/images/logoMedia/AgenciaOGloboCinza.png",
      economiaSC:"/images/logoMedia/EconomiaSCCinza.png",
      imobileReport:"/images/logoMedia/ImobliReportCinza.png",
      peqEmpresasGrandesNegocios:"/images/logoMedia/PequenasEmpresasGrandeNegociosCinza.png",
      valorEconomico:"/images/logoMedia/ValorEconomicoCinza.png",
    },
  },
  logoPartners: {
    gray: {
      bari: "/images/LogoPartners/gray/LogoBancoBari.svg",
      daycoval: "/images/LogoPartners/gray/LogoBancoDaycoval.svg",
      inter: "/images/LogoPartners/gray/LogoBancoInter.svg",
      cashme: "/images/LogoPartners/gray/LogoCashMe.svg",
      creditas: "/images/LogoPartners/gray/LogoCreditas.svg",
      itau: "/images/LogoPartners/gray/LogoItau.svg",
      libra: "/images/LogoPartners/gray/LogoLibra.svg",
      piratini: "/images/LogoPartners/gray/LogoPiratini.svg",
      pontte: "/images/LogoPartners/gray/LogoPontte.svg",
      rodobens: "/images/LogoPartners/gray/LogoRodobens.svg",
      santander: "/images/LogoPartners/gray/LogoSantander.svg",
      wimo: "/images/LogoPartners/gray/LogoWimo.svg",
    },
    colorfull: {
      bari: "/images/LogoPartners/colorfull/LogoBancoBari.svg",
      daycoval: "/images/LogoPartners/colorfull/LogoDaycoval.svg",
      inter: "/images/LogoPartners/colorfull/LogoIntersvg",
      cashme: "/images/LogoPartners/colorfull/LogoCashme.svg",
      creditas: "/images/LogoPartners/colorfull/LogoCreditas.svg",
      itau: "/images/LogoPartners/colorfull/LogoItau.svg",
      libra: "/images/LogoPartners/colorfull/LogoLibra.svg",
      piratini: "/images/LogoPartners/colorfull/LogoPiratini.svg",
      pontte: "/images/LogoPartners/colorfull/LogoPonttesvg",
      rodobens: "/images/LogoPartners/colorfull/LogoRodobens.svg",
      santander: "/images/LogoPartners/colorfull/LogoSantander.svg",
      wimo: "/images/LogoPartners/colorfull/LogoWimo.svg",
    },
    white: {
      bari: "/images/LogoPartners/white/LogoBancoBari.svg",
      daycoval: "/images/LogoPartners/white/LogoBancoDaycoval.svg",
      inter: "/images/LogoPartners/white/LogoBancoInter.svg",
      cashme: "/images/LogoPartners/white/LogoCashme.svg",
      creditas: "/images/LogoPartners/white/LogoCreditas.svg",
      itau: "/images/LogoPartners/white/LogoItau.svg",
      libra: "/images/LogoPartners/white/LogoLibra.svg",
      piratini: "/images/LogoPartners/white/LogoPiratini.svg",
      pontte: "/images/LogoPartners/white/LogoPontte.svg",
      rodobens: "/images/LogoPartners/white/LogoRodobens.svg",
      santander: "/images/LogoPartners/white/LogoSantander.svg",
      wimo: "/images/LogoPartners/white/LogoWimo.svg",
    },
  },
  bestCar:{
    carroNotas: "/images/BestCar/CARRO_1.png",
    gráficoBestCar: "/images/BestCar/gráficobestCar.svg",
    carro: "/images/BestCar/CARRO_2.png",
    gráficoFinan: "/images/BestCar/GRÁFICO_FINANCIAMENTO.svg",
    imgMulher: "/images/BestCar/IMAGEM_MULHER.png"
  },
};

export default image;
