const image = {
  logoSejabest: "https://res.cloudinary.com/djheoavst/image/upload/v1655833875/SejaBest/Logotipo-horizontal-principal-azul_e_degrade_plodag.png",
  logoSejabestWhite: "https://res.cloudinary.com/djheoavst/image/upload/v1654105983/SejaBest/Logotipo-horizontal-principal-branco_v0fler_k6prka.png",
  logoSejabestCinza:"https://res.cloudinary.com/djheoavst/image/upload/v1656078910/SejaBest/Logotipo-horizontal-principal-cinza_ftyqlw.png",
  bacen:"https://res.cloudinary.com/djheoavst/image/upload/v1656078765/Imagens%20site/bacen-grey_uj4mls.svg",
  arrow:"https://res.cloudinary.com/djheoavst/image/upload/v1656417395/Imagens%20site/Layout_-_1080x1080-1_hjk7cn.png",
  bestHub:"https://res.cloudinary.com/djheoavst/image/upload/v1656420035/Imagens%20site/besthub_q8ccip_1_ehospe.png",
  bestHubMockup:"https://res.cloudinary.com/djheoavst/image/upload/v1656421563/mockups/Alavanque_seus_resultados_com_o_BestHub__1_-removebg-preview_i70f35_jtndju.png",
  bestHubGif:"https://res.cloudinary.com/djheoavst/image/upload/v1656692109/mockups/Como_o_BestHub_pode_ajudar_o_seu_neg%C3%B3cio_4_xtov5m.png",
  bestHubMockupMob:"https://res.cloudinary.com/djheoavst/image/upload/v1656354075/mockups/cel_lxw2h6.png",
  bestHubMockupMd:"https://res.cloudinary.com/djheoavst/image/upload/v1656610812/mockups/Como_o_BestHub_pode_ajudar_o_seu_neg%C3%B3cio_2_uglkku.png",
  logoItau:"https://res.cloudinary.com/djheoavst/image/upload/v1656439002/Imagens%20site/logosbancosembranco/Itau2_1_rampca.png",
  logoSantander:"https://res.cloudinary.com/djheoavst/image/upload/v1656438974/Imagens%20site/logosbancosembranco/santander_branco_xjxqrg.png",
  logoPontte:"https://res.cloudinary.com/djheoavst/image/upload/v1656438961/Imagens%20site/logosbancosembranco/pontte2_1_emgpcl.png",
  logoCreditas:"https://res.cloudinary.com/djheoavst/image/upload/v1656438979/Imagens%20site/logosbancosembranco/Creditas_gsxcsh.png",
  logoPiratini:"https://res.cloudinary.com/djheoavst/image/upload/v1656438644/Imagens%20site/logosbancosembranco/CHP_Piratini_va8xio.png",
  logoCashme:"https://res.cloudinary.com/djheoavst/image/upload/v1656438644/Imagens%20site/logosbancosembranco/cashme_fnbpqy.png",
  logoBari:"https://res.cloudinary.com/djheoavst/image/upload/v1656438644/Imagens%20site/logosbancosembranco/Bari_ankpvr.png",
  banks:"https://res.cloudinary.com/djheoavst/image/upload/v1656685920/Imagens%20site/Como_o_BestHub_pode_ajudar_o_seu_neg%C3%B3cio_3_jx7mvs.png",
  icons:{
    phone:"https://res.cloudinary.com/djheoavst/image/upload/v1656360913/Sejabest-Icones/Filled%20%28preenchido%29/Smartphone-filled_yzxtzy.svg",
    calendar:"https://res.cloudinary.com/djheoavst/image/upload/v1656360905/Sejabest-Icones/Filled%20%28preenchido%29/Calendario-filled_tbhh1l.svg",
    user:"https://res.cloudinary.com/djheoavst/image/upload/v1656360914/Sejabest-Icones/Filled%20%28preenchido%29/Usuario-filled_vid1e4.svg",
    percentage:"https://res.cloudinary.com/djheoavst/image/upload/v1656360911/Sejabest-Icones/Filled%20%28preenchido%29/Porcentagem-filled_gst4hx.svg",
    money:"https://res.cloudinary.com/djheoavst/image/upload/v1656360907/Sejabest-Icones/Filled%20%28preenchido%29/Dinheiro-filled_shecwg.svg",
    house:"https://res.cloudinary.com/djheoavst/image/upload/v1656360905/Sejabest-Icones/Filled%20%28preenchido%29/Casa-filled_c4io8v.svg",
    phoneWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360656/Sejabest-Icones/Outline-branco/Smartphone-outline-branco_oinsxv.svg",
    userWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360657/Sejabest-Icones/Outline-branco/Usuario-outline-branco_nsb99j.svg",
    pcWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360653/Sejabest-Icones/Outline-branco/Notebook-outline-branco_wsbxow.svg",
    moneyWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360649/Sejabest-Icones/Outline-branco/Dinheiro-outline-branco_l3dso9.svg",
    percentageWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360653/Sejabest-Icones/Outline-branco/Porcentagem-outline-branco_wgre55.svg",
    calendarWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360647/Sejabest-Icones/Outline-branco/Calendario-outline-branco_q67zii.svg",
    houseWhite:"https://res.cloudinary.com/djheoavst/image/upload/v1656360647/Sejabest-Icones/Outline-branco/Casa-outline-branco_qboapb.svg",
  },
  
};

export default image;
